
[YouTube]
enabled = true
build-mode = "apk"
arch = "all"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
exclusive-patches = true
included-patches = """\
    'Hide ads' \
    'Disable player popup panels' \
    'Spoof video streams' \
    'Bypass URL redirects' \
    'Sanitize sharing links' \
    'Downloads' \
    'Theme' \
    'Return YouTube Dislike' \
    'Remove viewer discretion dialog' \
    'Spoof app version' \
    'Video ads' \
    'Disable resuming Shorts on startup' \
    'Force original audio' \
    'Remove background playback restrictions' \
    """

[Music]
enabled = true
patches-source = "anddea/revanced-patches"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patcher-args = """\
    -e 'Custom branding name for YouTube Music' -OappNameNotification='YT Music' -OappNameLauncher='YT Music' \
    -e 'Custom branding icon for YouTube Music' -OappIcon='YouTube Music' \
    """
excluded-patches = """\
    'SponsorBlock' \
    'Return YouTube Username' \
    'Disable Cairo splash animation' \
    'Disable QUIC protocol' \
    """

[GooglePhotos]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"
